### PR TITLE
fix: avoid concurrent read/write in metadata (#494)

### LINKED ISSUE #493: Race condition, errors out with Error: rpc error: code = Canceled desc = context canceled
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform v0.12.24

### Provider Version
+ provider.aws v2.56.0
+ provider.helm v1.2.1
+ provider.kubernetes v1.11.1
+ provider.postgresql v1.5.0

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

```hcl
resource "helm_release" "cert-manager" {
  chart = "jetstack/cert-manager"
  repository = "https://charts.jetstack.io"
  version = "v0.15.0-alpha.0"
  name = "cert-manager"
  namespace = "ingress"
  values = [
    file("./helm_vals/cert-manager.yaml")
  ]
  depends_on = [kubernetes_namespace.ingress, module.bi0]
}
```

### Debug Output

https://gist.github.com/ishioni/c48437786f7d1211038822fb39227968

### Expected Behavior

Plan should execute without error
### Actual Behavior

It randomly crashes with 

```
2020-05-11T12:44:00.105+0200 [DEBUG] plugin: plugin exited
Error: rpc error: code = Canceled desc = context canceled



Error: rpc error: code = Unavailable desc = transport is closing
```
### Steps to Reproduce

1. `terraform plan`

### LINKED ISSUE #494: Multiple helm_release resources concurrency issue (fatal error: concurrent map read and map write)
TL;DR: I created my own wrapper module (see below) for Helm provider's `helm_release` resource. I use that wrapper module multiple times in my `main.tf` to roll out complete stack for my cluster (see below). I experience random crashes during terraform plan and apply:
```log
Error: rpc error: code = Unavailable desc = transport is closing
Error: rpc error: code = Unavailable desc = transport is closing
Error: rpc error: code = Unavailable desc = transport is closing
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

* `Terraform v0.12.24` and `v0.12.25` (always hangs)
* `terragrunt version v0.23.10` and `v0.23.18`
### Provider Version
* `terraform-provider-helm_v1.2.1_x4`

### Affected Resource(s)

- `helm_release`

### Terraform Configuration Files

[kubernetes-services-copy.zip](https://github.com/terraform-providers/terraform-provider-helm/files/4609043/kubernetes-services-copy.zip)

##### Stack Trace
```
fatal error: concurrent map read and map write

goroutine 31 [running]:
runtime.throw(0x2c94295, 0x21)
	/opt/goenv/versions/1.13.7/src/runtime/panic.go:774 +0x72 fp=0xc000aa7020 sp=0xc000aa6ff0 pc=0x102e112
runtime.mapaccess2_faststr(0x2957ac0, 0xc0002aa360, 0xc000432700, 0x1b, 0x1, 0xc000432700)
	/opt/goenv/versions/1.13.7/src/runtime/map_faststr.go:116 +0x48f fp=0xc000aa7090 sp=0xc000aa7020 pc=0x1012bdf
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*DiffFieldReader).ReadField(0xc0002aa300, 0xc0006d2720, 0x3, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5555555555555555, ...)
	github.com/terraform-providers/terraform-provider-helm/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/field_reader_diff.go:51 +0x10d fp=0xc000aa71d0 sp=0xc000aa7090 pc=0x197623d
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*MultiLevelFieldReader).ReadFieldMerge(0xc000b05940, 0xc0006d2720, 0x3, 0x3, 0x2c5b89f, 0x3, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/terraform-providers/terraform-provider-helm/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/field_reader_multi.go:45 +0x1d8 fp=0xc000aa72e0 sp=0xc000aa71d0 pc=0x19796b8
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*ResourceData).get(0xc000116540, 0xc0006d2720, 0x3, 0x3, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/terraform-providers/terraform-provider-helm/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource_data.go:537 +0x2f8 fp=0xc000aa73c8 sp=0xc000aa72e0 pc=0x1986128
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*ResourceData).getRaw(0xc000116540, 0xc0004326e0, 0x1b, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/terraform-providers/terraform-provider-helm/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource_data.go:128 +0x75 fp=0xc000aa7430 sp=0xc000aa73c8 pc=0x19837c5
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*ResourceData).GetOk(0xc000116540, 0xc0004326e0, 0x1b, 0x2c6c3d0, 0xe, 0xc0004326e0)
	github.com/terraform-providers/terraform-provider-helm/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource_data.go:94 +0x5f fp=0xc000aa74e0 sp=0xc000aa7430 pc=0x198351f
github.com/terraform-providers/terraform-provider-helm/helm.k8sGetOk(0xc000116540, 0x2c6c3d0, 0xe, 0x24, 0x0, 0x0)
	github.com/terraform-providers/terraform-provider-helm/helm/provider.go:268 +0x93 fp=0xc000aa7588 sp=0xc000aa74e0 pc=0x27709b3
github.com/terraform-providers/terraform-provider-helm/helm.(*KubeConfig).toRawKubeConfigLoader(0xc0006d2060, 0x0, 0x0)
	github.com/terraform-providers/terraform-provider-helm/helm/structure_kubeconfig.go:86 +0xd38 fp=0xc000aa7718 sp=0xc000aa7588 pc=0x277bc68
github.com/terraform-providers/terraform-provider-helm/helm.(*KubeConfig).ToRawKubeConfigLoader(0xc0006d2060, 0x0, 0x0)
	github.com/terraform-providers/terraform-provider-helm/helm/structure_kubeconfig.go:68 +0xab fp=0xc000aa7780 sp=0xc000aa7718 pc=0x277aecb
github.com/terraform-providers/terraform-provider-helm/helm.(*KubeConfig).ToRESTConfig(0xc0006d2060, 0x0, 0x0, 0x0)
	github.com/terraform-providers/terraform-provider-helm/helm/structure_kubeconfig.go:31 +0x2b fp=0xc000aa77b0 sp=0xc000aa7780 pc=0x277ab1b
k8s.io/kubectl/pkg/cmd/util.(*factoryImpl).ToRESTConfig(...)
	github.com/terraform-providers/terraform-provider-helm/vendor/k8s.io/kubectl/pkg/cmd/util/factory_client_access.go:63
k8s.io/kubectl/pkg/cmd/util.(*factoryImpl).KubernetesClientSet(0xc0006d2090, 0x0, 0x0, 0x0)
	github.com/terraform-providers/terraform-provider-helm/vendor/k8s.io/kubectl/pkg/cmd/util/factory_client_access.go:79 +0x38 fp=0xc000aa77e0 sp=0xc000aa77b0 pc=0x25167e8
helm.sh/helm/v3/pkg/kube.(*Client).IsReachable(0xc0006d20c0, 0x1983656, 0x28d1360)
	github.com/terraform-providers/terraform-provider-helm/vendor/helm.sh/helm/v3/pkg/kube/client.go:91 +0x37 fp=0xc000aa7840 sp=0xc000aa77e0 pc=0x2518be7
helm.sh/helm/v3/pkg/action.(*Get).Run(0xc000aa78d0, 0xc000744960, 0x12, 0x28d1360, 0x28d1360, 0x3012010)
	github.com/terraform-providers/terraform-provider-helm/vendor/helm.sh/helm/v3/pkg/action/get.go:41 +0x3b fp=0xc000aa7888 sp=0xc000aa7840 pc=0x271acab
github.com/terraform-providers/terraform-provider-helm/helm.getRelease(0xc000a192c0, 0xc000744960, 0x12, 0x28d1360, 0xc0006ced50, 0x1)
	github.com/terraform-providers/terraform-provider-helm/helm/resource_release.go:894 +0x64 fp=0xc000aa7900 sp=0xc000aa7888 pc=0x2778fe4
github.com/terraform-providers/terraform-provider-helm/helm.resourceReleaseExists(0xc0002aca10, 0x2a55f40, 0xc0002aa2a0, 0xc0002aca10, 0x0, 0x0)
	github.com/terraform-providers/terraform-provider-helm/helm/resource_release.go:730 +0x10b fp=0xc000aa7958 sp=0xc000aa7900 pc=0x277748b
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000596c60, 0xc000b685a0, 0x2a55f40, 0xc0002aa2a0, 0xc000146960, 0x0, 0x0)
	github.com/terraform-providers/terraform-provider-helm/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:445 +0x24d fp=0xc000aa79c8 sp=0xc000aa7958 pc=0x19812dd
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00000ebc8, 0x3098960, 0xc000573020, 0xc00013c720, 0xc00000ebc8, 0xc000573020, 0xc0006b5b30)
	github.com/terraform-providers/terraform-provider-helm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:525 +0x3d8 fp=0xc000aa7ad0 sp=0xc000aa79c8 pc=0x19a0b28
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x2bc4c00, 0xc00000ebc8, 0x3098960, 0xc000573020, 0xc00013c6c0, 0x0, 0x3098960, 0xc000573020, 0xc000684580, 0x54a)
	github.com/terraform-providers/terraform-provider-helm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3269 +0x217 fp=0xc000aa7b40 sp=0xc000aa7ad0 pc=0x18b2787
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00053fb00, 0x30c10e0, 0xc000532780, 0xc00013a200, 0xc0003063c0, 0x4108710, 0x0, 0x0, 0x0)
	github.com/terraform-providers/terraform-provider-helm/vendor/google.golang.org/grpc/server.go:1024 +0x4f4 fp=0xc000aa7e18 sp=0xc000aa7b40 pc=0x147ad24
google.golang.org/grpc.(*Server).handleStream(0xc00053fb00, 0x30c10e0, 0xc000532780, 0xc00013a200, 0x0)
	github.com/terraform-providers/terraform-provider-helm/vendor/google.golang.org/grpc/server.go:1313 +0xd97 fp=0xc000aa7f48 sp=0xc000aa7e18 pc=0x147ea47
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0004ba890, 0xc00053fb00, 0x30c10e0, 0xc000532780, 0xc00013a200)
	github.com/terraform-providers/terraform-provider-helm/vendor/google.golang.org/grpc/server.go:722 +0xbb fp=0xc000aa7fb8 sp=0xc000aa7f48 pc=0x148be9b
runtime.goexit()
	/opt/goenv/versions/1.13.7/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000aa7fc0 sp=0xc000aa7fb8 pc=0x105b761
created by google.golang.org/grpc.(*Server).serveStreams.func1
	github.com/terraform-providers/terraform-provider-helm/vendor/google.golang.org/grpc/server.go:720 +0xa1
```

##### Full Stack Trace
https://gist.github.com/krzysztof-miemiec/2d44d187a75a2f106ccd9c71fbf67883

### Expected Behavior

Helm properly plans and applies changes to multiple releases.

### Actual Behavior

Random crashes happen during plan phase (I provided stack trace for that) OR sometimes everything gets stuck during deployment (no logs 😞).

### Steps to Reproduce

1. Have Kubernetes cluster up and running, be able to freely access it via configured context
1. Download zip file attached
1. `terraform plan`

### Important Factoids
I never debugged or contributed to any Go tool, so these are mostly guesses based on my knowledge of Terraform:
* It happens randomly, I guess it occurs more often when you define more `helm_release` resources (it probably won't occur when multiple instances of helm provider are not running at the same time 🤔)
* I noticed that it takes ages to refresh state of Helm resources, especially ones that are using CRDs (not the ones that define them). Using `-parallelism=1` flag helps a bit with performance and with this flag I didn't encounter crashes or infinite wait on plan phase.
* Infinite wait happens sometimes during `terraform apply` even with `wait = false`.
* If I understand stack trace correctly, it is a concurrency issue with Helm provider or Terraform itself

### References

- https://github.com/terraform-providers/terraform-provider-helm/issues/486 - same user-facing error message, but I guess the cause is different
- https://github.com/hashicorp/terraform/issues/24589 - similar root cause, issue is closed, PR's merged, but it's not released yet

### PR DESCRIPTION
**Pull request by krzysztof-miemiec**
### Description
After debugging and collecting info on #494, I made a noticable change in the way Kubernetes config is loaded. This change is required to avoid `concurrent map read and write` errors. While reading readource data from `Meta` object, Helm Provider did use locking, but on `KubeConfig` and not on `Meta` object itself. This caused the error. I guess this PR might've been smaller if I used locking on `Meta` in `ToRawKubeConfigLoader` function. However we have no access to `Meta` there and I wanted to keep `KubeConfig` structure as small and independent as possible. 

Possible downsides: I probably decreased the performance of Helm Provider - there's no caching of client.
Possible solution (my guess): add a `map[string]*action.Configuration` to `Meta` and cache Helm configuration per each namespace?

* Fix: Looks like rewriting code related to Helm configuration creation (Kubeconfig structure) does the trick - I'm not sure of performance and memory consumption implications though
* Improvement: Use `logId` to log out more details (function and name of resource) when running with `TF_LOG=DEBUG` environmental variable

### Acceptance tests
- [x] Have you added an acceptance test for the functionality being added?
- [x] Have you run the acceptance tests on this branch? (If so, please include the test log in a gist)

You can see the test log for this PR here: https://gist.github.com/krzysztof-miemiec/5f2fd076171dc584af9b5c1b7beb389d

Previously there was no acceptance test which checked simultaneous deployment of multiple resources at the same time. I added a test case for that. To make things fast and simple, I added a chart fixture containing a simple `ConfigMap` deployment. 

I also ran my new test against the old codebase, getting `fatal error: concurrent map read and map write` 8 out of 10 attempts. I don't know how to reproduce it 10/10 times, but the test behaves like just like real-world scenario. After changes in this PR, the test passes 10/10 times.

Sidenote: I run tests on Docker Desktop on Mac w/ Kubernetes enabled. Tests take a lot of time and fail if you have poor Internet connection - is it necessary to pull external charts like MariaDB?

### References
- fixes #494 
- probably also fixes #493

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### CODE REVIEW

**Comment by krzysztof-miemiec** [comment]
@aareet Can you take a look at this PR? 🙏

File: helm/resource_release_test.go [hunk 1]
```diff
@@ -113,6 +113,52 @@ func TestAccResourceRelease_import(t *testing.T) {
...
+		return fmt.Sprintf(`
+			resource "helm_release" %q {
+				name        = %q
+				namespace   = %q
+				chart       = "./test-fixtures/charts/basic-chart"
+
+				set {
+					name = %q
+					value = %q
+                }
```
Comment (jrhouston) [inline helm/resource_release_test.go]: Need to fix the formatting here

File: helm/resource_release_test.go [hunk 2]
```diff
@@ -113,6 +113,52 @@ func TestAccResourceRelease_import(t *testing.T) {
 	})
 }
 
+func TestAccResourceRelease_multiple_charts(t *testing.T){
```
Comment (jrhouston) [inline helm/resource_release_test.go]: Need to run go formatter on this - just run `make fmt` at the top level.

File: helm/resource_release.go [hunk 3]
```diff
@@ -889,11 +908,24 @@ func logValues(values map[string]interface{}, d resourceGetter) error {
...
 }
 
-func getRelease(cfg *action.Configuration, name string) (*release.Release, error) {
+func getRelease(m *Meta, cfg *action.Configuration, name string) (*release.Release, error) {
+	debug("%s getRelease wait for lock", name)
+	m.Lock()
+	defer m.Unlock()
+	debug("%s getRelease got lock, started", name)
+
+	cfg.Log = debug
```
Comment (jrhouston) [inline helm/resource_release.go]: Can you help me understand why we had to set this and the one below?

This should get set to `debug` in [GetHelmConfiguration](https://github.com/hashicorp/terraform-provider-helm/blob/master/helm/provider.go#L319) which in turn should set it on Releases.Log in the helm actions package [here](https://github.com/helm/helm/blob/9b42702a4bced339ff424a78ad68dd6be6e1a80a/pkg/action/action.go#L232).

**Review by jrhouston — CHANGES_REQUESTED** [review]
Thanks so much for taking this on @krzysztof-miemiec! Just a couple of things.

File: helm/resource_release.go (hunk 3 above)
Comment (krzysztof-miemiec) [reply helm/resource_release.go]: Oops, this is a leftover from my debugging session - thanks for pointing that out!

File: helm/resource_release_test.go (hunk 1 above)
Comment (krzysztof-miemiec) [reply helm/resource_release_test.go]: This is weird - it looks like this line has indentation made with spaces and not with tabs - will fix that 👍

**Comment by krzysztof-miemiec** [comment]
@jrhouston thank you for pointing out the issues - I applied fixes and rebased my branch on current `master`.

**Review by jrhouston — APPROVED** [review]
