### PR TITLE
Fix repo/chart path bug causing unexpected diff

### LINKED ISSUE #448: Helm provider 1.1 constantly updating helm_release
# Terraform Version
0.12.24

### Affected Resource(s)
- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "cert_manager" {
  name      = "cert-manager"
  chart     = "jetstack/cert-manager"
  namespace = kubernetes_namespace.cert_manager.id
  version   = "v0.13.0"
```

### Expected Behavior
No changes after chart has been applied.

### Actual Behavior
Every time chart is read as `cert-manager`. Same for `stable/*` charts.
This only happens in newly released 1.1 version.

```
  # helm_release.cert_manager will be updated in-place
  ~ resource "helm_release" "cert_manager" {
        atomic                     = false
      ~ chart                      = "cert-manager" -> "jetstack/cert-manager"
```

### PR DESCRIPTION
**Pull request by jrhouston**
Resolves #448

### CODE REVIEW

File: helm/resource_release.go [hunk 1]
```diff
@@ -890,6 +887,7 @@ func resourceHelmReleaseImportState(d *schema.ResourceData, meta interface{}) ([
 
 	d.Set("name", r.Name)
 	d.Set("description", r.Info.Description)
+	d.Set("chart", r.Chart.Metadata.Name)
```
Comment (dak1n1) [inline helm/resource_release.go:890]: I ran a lint tool on this and it mentioned the error return value isn't being checked for this one. It could be fine. But I'll post the output here just in case:

```
[dakini@dax terraform-provider-helm ((cbb5efb...))]$ golangci-lint run
helm/resource_release.go:888:7: Error return value of `d.Set` is not checked (errcheck)
        d.Set("name", r.Name)
             ^
helm/resource_release.go:889:7: Error return value of `d.Set` is not checked (errcheck)
        d.Set("description", r.Info.Description)
             ^
helm/resource_release.go:890:7: Error return value of `d.Set` is not checked (errcheck)
        d.Set("chart", r.Chart.Metadata.Name)
             ^
helm/resource_release.go:831:5: S1003: should use !strings.Contains(name, "/") instead (gosimple)
        if strings.Index(name, "/") == -1 && repository != "" {
           ^
helm/provider.go:462:27: S1019: should use make([]string, len(s)) instead (gosimple)
        result := make([]string, len(s), len(s))
```

Comment (jrhouston) [reply helm/resource_release.go:890]: Yeah - there is a bunch of linter problems with this repo but it shouldn't be a problem for this particular bug. We should totally clean these up though.

**Review by dak1n1 — APPROVED** [review]
LGTM
