### PR TITLE
Fix install errors being swallowed when creating a helm_release

### LINKED ISSUE #398: helm_release stuck in `pending-install`
### Summary

helm chart stuck in `pending-install` phase. I tried installing a helm_chart using the v1.0.0 provider, but the chart doesn't get installed and the plugin reports that the install was successful.

When I run `terraform state show helm_release.cluster_autoscaler`, it seems to be stuck in `pending-install` state.

### Terraform Version
```
% terraform -v
Terraform v0.12.16
+ provider.aws v2.47.0
+ provider.helm v1.0.0
+ provider.kubernetes v1.10.0
+ provider.null v2.1.2
+ provider.template v2.1.2
```

### Affected Resource(s)

- helm_release
- helm_chart: stable/cluster_autoscaler
- kubernetes version: 1.14 (AWS EKS)

### Terraform Configuration Files
```hcl

provider "helm" {
  version = "~> 1.0"
  kubernetes {
    host                   = aws_eks_cluster.libra.endpoint
    cluster_ca_certificate = base64decode(aws_eks_cluster.libra.certificate_authority.0.data)
    token                  = data.aws_eks_cluster_auth.libra.token
    load_config_file       = false
  }
}

data "helm_repository" "stable" {
  name = "stable"
  url  = "https://kubernetes-charts.storage.googleapis.com"
}

resource "helm_release" "cluster_autoscaler" {
  name       = "cluster_autoscaler"
  repository = data.helm_repository.stable.metadata[0].name
  chart      = "cluster-autoscaler"

  set {
    name  = "awsRegion"
    value = var.region
  }

  set {
    name  = "rbac.create"
    value = "true"
  }

  set {
    name  = "rbac.serviceAccountAnnotations.eks\\.amazonaws\\.com/role-arn"
    value = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/${local.cluster_name}-cluster-autoscaler"
  }

  set {
    name  = "autoDiscovery.enabled"
    value = "true"
  }

  set {
    name  = "autoDiscovery.clusterName"
    value = local.cluster_name
  }

  depends_on = [null_resource.bootstrap_cluster]
}
```

### Debug Output

```
helm_release.cluster_autoscaler: Creating...
helm_release.cluster_autoscaler: Creation complete after 4s [id=cluster_autoscaler]
```

```
% terraform state show helm_release.cluster_autoscaler
# helm_release.cluster_autoscaler:
resource "helm_release" "cluster_autoscaler" {
    atomic                = false
    chart                 = "cluster-autoscaler"
    cleanup_on_fail       = false
    dependency_update     = false
    disable_crd_hooks     = false
    disable_webhooks      = false
    force_update          = false
    id                    = "cluster_autoscaler"
    max_history           = 0
    metadata              = [
        {
            chart     = "cluster-autoscaler"
            name      = "cluster_autoscaler"
            namespace = "kube-system"
            revision  = 1
            values    = jsonencode(
                {
                    autoDiscovery = {
                        clusterName = "kush-k8s-testnet"
                        enabled     = true
                    }
                    awsRegion     = "us-west-2"
                    rbac          = {
                        create                    = true
                        serviceAccountAnnotations = {
                            eks.amazonaws.com/role-arn = "xxx"
                        }
                    }
                }
            )
            version   = "6.4.0"
        },
    ]
    name                  = "cluster_autoscaler"
    namespace             = "kube-system"
    recreate_pods         = false
    render_subchart_notes = true
    replace               = false
    repository            = "stable"
    reset_values          = false
    reuse_values          = false
    skip_crds             = false
    status                = "pending-install"
    timeout               = 300
    verify                = false
    version               = "6.4.0"
    wait                  = true

    set {
        name  = "autoDiscovery.clusterName"
        value = "kush-k8s-testnet"
    }
    set {
        name  = "autoDiscovery.enabled"
        value = "true"
    }
    set {
        name  = "awsRegion"
        value = "us-west-2"
    }
    set {
        name  = "rbac.create"
        value = "true"
    }
    set {
        name  = "rbac.serviceAccountAnnotations.eks\\.amazonaws\\.com/role-arn"
        value = "xxx"
    }
}

% helm list --all-namespaces
NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART	APP VERSION
```

### PR DESCRIPTION
**Pull request by jrhouston**
Resolves #398 #401 #404

### CODE REVIEW

File: helm/resource_release_test.go [hunk 1]
```diff
@@ -346,10 +366,10 @@ func TestAccResourceRelease_updateAfterFail(t *testing.T) {
 			ExpectError:        regexp.MustCompile("invalid resource name"),
 			ExpectNonEmptyPlan: true,
 		}, {
-			Config: testAccHelmReleaseConfigBasic(testResourceName, namespace, name, "7.1.0"),
+			Config: fixed,
```
Comment (jrhouston) [inline helm/resource_release_test.go:369]: This was actually (successfully) testing the wrong thing. Here we want to make a release for a chart that would fail, then install the same chart again successfully.

File: helm/resource_release_test.go [hunk 2]
```diff
@@ -433,6 +453,78 @@ func TestAccResourceRelease_updateVersionFromRelease(t *testing.T) {
...
+		chart       = "nginx-ingress"
+	}`, namespace)
+
+	resource.ParallelTest(t, resource.TestCase{
+		PreCheck:     func() { testAccPreCheck(t, namespace) },
+		Providers:    testAccProviders,
+		CheckDestroy: testAccCheckHelmReleaseDestroy(namespace),
+		Steps: []resource.TestStep{{
+			Config:             broken,
+			ExpectError:        regexp.MustCompile("create: failed to create"),
```
Comment (jrhouston) [inline helm/resource_release_test.go:522]: There is a bug in helm (https://github.com/helm/helm/issues/3493) where it does not validate the release name before trying to create the ConfigMap for it. So here you get a lengthy error message from deep in the bowels of k8s. I've left this test case vague because I expect the error message will change to something more human friendly soon. 

I'm aware that the validation for the release name is actually just RFC1123, but I think we should expect helm and kubernetes to give us back an error instead of duplicating the validation in the provider.

File: helm/resource_release.go [hunk 3]
```diff
@@ -414,14 +414,27 @@ func resourceReleaseCreate(d *schema.ResourceData, meta interface{}) error {
...
 
-	// Return error only if no release was created
-	// This will ensure we store even failed releases into the state
 	if err != nil && rel == nil {
 		return err
-	} else if err != nil && rel.Info.Status == release.StatusFailed {
+	}
+
+	if err != nil && rel != nil {
+		exists, existsErr := resourceReleaseExists(d, meta)
```
Comment (jrhouston) [inline helm/resource_release.go:422]: There is a weird case you can run into where the above [Run](https://github.com/terraform-providers/terraform-provider-helm/pull/406/files#diff-70e42ed4d5009a76bddc6fb6c16b913bR415) function can return both an `error` and a `Release` object but the metadata for the release has not actually been persisted to a ConfigMap on the cluster. Here I am just explicitly checking that a release was indeed created.

**Comment by aaronmell** [comment]
LGTM
