### PR TITLE
Fix concurrency issues reading multiple repos

### LINKED ISSUE #271: Multiple helm_repository data providers overwrite eachother
### Terraform Version
Terraform v0.11.13
+ provider.helm v0.9.0
+ provider.kubernetes v1.6.2
+ provider.local v1.2.1
+ provider.null v2.1.1
+ provider.tls v1.2.0

### Affected Resource(s)
- helm_repository

### Terraform Configuration Files
```hcl
data "helm_repository" "incubator" {
  name = "some_chart"
  url  = "https://kubernetes-charts-incubator.storage.googleapis.com/"
}

data "helm_repository" "stable" {
  name = "another_chart"
  url  = "https://kubernetes-charts.storage.googleapis.com/"
}
```

### Expected Behavior
The repositories.yaml contains both entries.

### Actual Behavior
The repositories.yaml will only contain one of the entries.

### Steps to Reproduce

1. `terraform apply`

### PR DESCRIPTION
**Pull request by rporres**
Fixes #271

Signed-off-by: Rafael Porres Molina <rafa@sourced.tech>

### CODE REVIEW

**Comment by pdecat** [comment]
I'm currently looking into adding acceptance tests to reproduce this issue.

The work I've done in https://github.com/terraform-providers/terraform-provider-helm/pull/185 should help test this more repeatably, using a _fresh_ helm home on each run, even locally.

That's apparently an issue with helm itself. There was a [similar issue with helmfile](https://github.com/roboll/helmfile/issues/45) and [it was resolved by running the repo additions serially](https://github.com/roboll/helmfile/pull/46/files), just like is done in this PR with locking.

The same behavior is probably also happening when running `helm repo add` commands concurrently, but I did not find a matches in the helm github issue tracker. If that can be confirmed, that'll probably be worth reporting.

**Comment by pdecat** [comment]
It's confirmed to also be an issue with the `helm repo add` command, I've opened https://github.com/helm/helm/issues/5677

And I've managed to reproduce the issue with an acceptance test against `v0.9.0`, `v0.9.1` and `master`.
The same test passes on the `fix-271` branch.
Submitted #273.

File: helm/data_repository.go [hunk 1]
```diff
@@ -120,6 +120,8 @@ func getRepository(d *schema.ResourceData, m *Meta) (*repo.Entry, error) {
 }
 
 func addRepository(m *Meta, name, url string, home helmpath.Home, certFile, keyFile, caFile string, username string, password string) error {
+	m.Lock()
```
Comment (pdecat) [inline helm/data_repository.go:123]: Locking can probably happen later when reading from and writing to the repositories file is actually required.
This would allow downloading indexes in parallel.

The result of the `LoadRepositoriesFile()` call stored in `repoFile` is only needed after the index caching for `repoFile.Update()` at https://github.com/terraform-providers/terraform-provider-helm/pull/272/files#diff-a64ebd9d5beb4bea06b92cff0bddf4c7R152

The original helm implementation also checks if the repo does not already exists and doesn't need an update: https://github.com/helm/helm/blob/518a9d63e6cdcc06a816c6b6ca27ff36fe1636ec/cmd/helm/repo_add.go#L109
It may be useful to add an equivalent check before locking and rewriting the repositories file in order to skip no-op updates and reduce contention.

Note: locking only at the process level won't prevent concurrent processes from overwriting each others repositories additions when they share the same helm home. Process level mutex locking could be combined with file level locking to handle this.

Comment (pdecat) [reply helm/data_repository.go:123]: Using github.com/gofrs/flock for cross platform file locking for same process and concurrent processes synchronization eases that task: https://github.com/helm/helm/pull/5678/files#diff-13a230f2627b662a7d5319ba6c0d653cR139

Comment (rporres) [reply helm/data_repository.go:123]: I do agree that current implementation the issue of downloading the indexes every time and this fix won't make things faster.

Since we have a bug, what do you think about merging #273 here, merging this PR into master and release a new version with the fixes? I would create an issue with your suggestions for a better implementation so that it's worked while we have a less buggy version out there

Comment (pdecat) [reply helm/data_repository.go:123]: Agreed, let's do this.

Comment (pdecat) [reply helm/data_repository.go:123]: My PR implementing the fix using github.com/gofrs/flock on helm itself was just merged: https://github.com/helm/helm/pull/5678

Comment (pdecat) [reply helm/data_repository.go:123]: Feel free to merge https://github.com/terraform-providers/terraform-provider-helm/pull/273 here.

**Comment by rporres** [comment]
Merged https://github.com/terraform-providers/terraform-provider-helm/pull/273 here

**Comment by jpreese** [comment]
Thanks guys. I look forward to the next release. This'll speed up some of our configs quite a bit.
